package com.srbodroid.app.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.srbodroid.app.model.News;
import com.srbodroid.app.model.Image;
import com.srbodroid.app.model.Comment;

import com.srbodroid.app.model.NewsDao;
import com.srbodroid.app.model.ImageDao;
import com.srbodroid.app.model.CommentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDaoConfig;
    private final DaoConfig imageDaoConfig;
    private final DaoConfig commentDaoConfig;

    private final NewsDao newsDao;
    private final ImageDao imageDao;
    private final CommentDao commentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(ImageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        newsDao = new NewsDao(newsDaoConfig, this);
        imageDao = new ImageDao(imageDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);

        registerDao(News.class, newsDao);
        registerDao(Image.class, imageDao);
        registerDao(Comment.class, commentDao);
    }
    
    public void clear() {
        newsDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public ImageDao getImageDao() {
        return imageDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

}
